database:
  host: "localhost"
  port: "5432"
  user: "service_u"
  password: "123"
  db_name: "service_db"
  ssl_mode: "disable"
  max_connections: 5

kafka:
  brokers: ["localhost:9092"]
  topic: "orders"
  group_id: "order_processor"
  reader:
    min_bytes: 10240
    max_bytes: 10485760
    read_retry_delay: "1s"
    read_batch_timeout: "1s"
    commit_interval: "1s"
  writer:
    write_timeout: "10s"
    read_timeout: "10s"
    balancer: "least_bytes"

test:
  kafka:
    brokers: ["localhost:9092"]
    topic: "orders"
    integration_group_id: "test_producer"
    multiple_group_id: "test_multiple_producer"
    benchmark_group_id: "benchmark_producer"
    benchmark_topic: "benchmark_orders"

cache:
  shard_count: 32
  max_items: 100000
  ttl: "10m"
  cleanup_interval: "1m"

server:
  port: ":8080"
  shutdown_timeout: "10s"